name: infinite_canvas
description: >
  An extensible infinite canvas for Flutter based on InteractiveViewer 
  and CustomMultiChildLayout which allows for widgets to be used as 
  children and be moved or selected.
version: 0.0.8
repository: https://github.com/rodydavis/infinite_canvas

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0
  directed_graph: ^0.3.7
  vector_math: ^2.1.4

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:

screenshots:
  - description: "Example of multiple nodes on the canvas"
    path: screenshots/overview.png
  - description: "Drag handles for a selected node (if enabled)"
    path: screenshots/drag.png
  - description: "Example of menus that show for a selected node"
    path: screenshots/menu.png

scripts:
  example:
    - cd example && flutter build web && cd ..
    - dart doc -o example/build/web/docs
    - dhttpd --path example/build/web
